# Data paths
data:
  price_path: "data/raw/all_stocks_ohlcv.csv"
  sentiment_path: "data/sentiment/final_sentiment_panel.csv"

# Feature engineering parameters
feature_params:
  volatility_lookback: 20
  momentum_lookback: 10
  volume_lookback: 5

# Environment parameters
env_params:
  lookback_window: 20
  transaction_cost: 0.001
  initial_cash: 100000
  action_type: "discrete"  # or "continuous"

# Model parameters
model_params:
  ppo:
    learning_rate: 0.0003
    n_steps: 2048
    batch_size: 64
    n_epochs: 10
    gamma: 0.99
    gae_lambda: 0.95
    clip_range: 0.2
    ent_coef: 0.01
    vf_coef: 0.5
    max_grad_norm: 0.5
    
  dqn:
    learning_rate: 0.0001
    buffer_size: 100000
    learning_starts: 1000
    batch_size: 32
    tau: 1.0
    gamma: 0.99
    train_freq: 4
    gradient_steps: 1
    target_update_interval: 1000
    exploration_fraction: 0.1
    exploration_initial_eps: 1.0
    exploration_final_eps: 0.05

# Training parameters
training:
  total_timesteps: 1000000
  eval_freq: 10000
  n_eval_episodes: 10

# Validation parameters
validation:
  train_test_split: 0.8
  validation_episodes: 10 